services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: talently
      MYSQL_USER: default
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: talently
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"